version: '3.0'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: chaldeabot
      POSTGRES_PASSWORD: chaldeabot
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
    - "5432:5432"
  chaldeabot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;Port=5432;Database=chaldeabot;User Id=chaldeabot;Password=chaldeabot;
      - ASPNETCORE_URLS=http://*:80
      - USE_FORWARDED_HEADERS=true
    depends_on:
      - db
    build:
      context: .
    ports:
      - "5000:80"
volumes:
  dbdata:
    
networks:
  default:
    driver: bridge