version: '3.0'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: chaldeabot
      POSTGRES_PASSWORD: chaldeabot
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
    - "5432:5432"
    container_name: chaldeabot_db
  chaldeabot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Port=5432;Database=chaldeabot;User Id=chaldeabot;Password=chaldeabot;
      - ASPNETCORE_URLS=http://*:5000
      - USE_FORWARDED_HEADERS=true
      - MIGRATE=true
      # - SEED=true
      # - MODE=webhook|polling
      # - BasePath=/telegram/
      # - BotKey=00000:XXXXXXXXXXXXXXXXXXXXX
      # - BaseUrl=https://localhost
      # - Rayshift__ApiKey=XXXXXXXXXXXXXXXXXXXX
    depends_on:
      - db
    build:
      context: src/
      dockerfile: Server/Dockerfile
    ports:
      - "5000:5000"
    container_name: chaldeabot_bot
volumes:
  dbdata:
    
networks:
  default:
    driver: bridge