version: '3.0'

services:
  chaldeabot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - USE_FORWARDED_HEADERS=true
    restart: always
    container_name: chaldeabot_bot
  db:
    container_name: chaldeabot_db