<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="nunit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Server\Server.csproj" />
    <ProjectReference Include="..\FgoData\FgoData.csproj" />
  </ItemGroup>
</Project>
