name: Build Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Install dependencies
      run: dotnet restore ChaldeaBot.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ChaldeaBot.sln
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal ChaldeaBot.sln
